image: registry.qtt6.cn/fe/fe-service-oss-deploy:qtt

before_script:
  - mkdir -p $QUKAN_NODE_MODULES/"$CI_PROJECT_PATH"/node_modules
  - cp package.json $QUKAN_NODE_MODULES/"$CI_PROJECT_PATH"/package.json
  - cd $QUKAN_NODE_MODULES/"$CI_PROJECT_PATH"
  - rm -f package-lock.json
  - npm i --registry=http://nexus.qutoutiao.net/repository/qtt/
  - cp -r $QUKAN_NODE_MODULES/"$CI_PROJECT_PATH"/node_modules $CI_PROJECT_DIR/node_modules
  - cd -

stages:
  - deploy-prd

deploy-prd:
  stage: deploy-prd
  only:
    - master
  script:
    - cp /home/deploy/deploy.js ./deploy.js
    - npm run build:qa
    - node ./deploy.js 5cc2b1614ac5e80124eb0fd2 "$CI_REPOSITORY_URL" "$CI_PROJECT_ID" "$CI_BUILD_REF_NAME" "$CI_COMMIT_SHA" "$CI_COMMIT_MESSAGE" ./docs qapp-docs
